version: "3.9"

services:
  credit-risk-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: credit-risk-api
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
